apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-log-analyzer
  namespace: ai-log-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-log-analyzer
  template:
    metadata:
      labels:
        app: ai-log-analyzer
    spec:
      containers:
        - name: ai-log-analyzer
          image: manishraut12/log-analyzer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5 
            failureThreshold: 5
