apiVersion: v1
kind: Service
metadata:
  name: ai-log-analyzer
  namespace: ai-log-analyzer
spec:
  type: NodePort
  selector:
    app: ai-log-analyzer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
